theme: jekyll-theme-architect

title: [Shoal]
description: [a java based scalable dynamic clustering framework that enables system development with fault 
tolerance, reliability and availability]

show_downloads: false

links:
  download: 
  mailinglist: 
  source: https://github.com/javaee/shoal
  