theme: jekyll-theme-architect

title: [Shoal]
description: [scalable dynamic clustering for fault tolerance, reliability and availability]

show_downloads: false

links:
  download: 
  mailinglist: 
  source: https://github.com/javaee/shoal
  
